### ISSUE TITLE
Doesn't update after wrong entry

### ISSUE THREAD

**Issue by sebasvanderplaat** [synobsys/mendix-ReCaptcha#1]
Hi, 

When I enter the text wrong and then try it again with the right text, I still get the message:

Your input does not match the displayed text

Only when I press on the refresh button on the recaptcha widget (to get a new image) then it works when I enter the text of the new image. 

This is not the behaviour I expect can you please help me with this issue?

Thanks!

**Comment by mgroeneweg** [comment]
Hi,

After entering an invalid response, the widget should show a new captcha image. I tried the test project in the repository, and this does work. Does your microflow set a return value when the entered value is incorrect? That would trigger the widget to get a new captcha image.

Please check against the test project.

**Comment by sebasvanderplaat** [comment]
Thanks,

The issue is fixed now!

Sebastiaan van der Plaat
Lead consultant
[cid:58C2F67D-F7CE-48C4-84E4-AC44B24ADA4F]   +44 7544267498
[cid:15FF6067-DF49-46F8-8FBF-83C323B3BCF6]   sebastiaan.van.der.plaat@mendix.com<mailto:sebastiaan.van.der.plaat@mendix.com>





[cid:2DD47304-99E8-438E-88FA-66AB4C32A20D]<http://www.mendix.com/?utm_source=email-signature&utm_medium=email&utm_campaign=mendix-signature>

**Comment by mgroeneweg** [comment]
:-)
